import PDFDocument from "pdfkit";
import type { Audit } from "@workspace/db";

export interface AuditContent {
  leaks: Array<{
    title: string;
    impact: "low" | "medium" | "high";
    estimatedMonthlyLossUsd: number;
    evidence: string;
    fix: string;
  }>;
  quickWins: string[];
  summary: string;
}

const COLORS = {
  bg: "#0b0f17",
  card: "#111827",
  border: "#1f2937",
  text: "#e6e8ee",
  mute: "#8b94a7",
  accent: "#6366f1",
  accentSoft: "#312e81",
  white: "#ffffff",
  high: "#ef4444",
  medium: "#f59e0b",
  low: "#10b981",
} as const;

function impactColor(impact: "low" | "medium" | "high"): string {
  return impact === "high"
    ? COLORS.high
    : impact === "medium"
      ? COLORS.medium
      : COLORS.low;
}

function formatUsd(n: number): string {
  return n.toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  });
}

/**
 * Render the Revenue Leak Audit as a branded multi-page PDF and resolve to
 * a Buffer. Uses pdfkit (no headless browser) so it runs on any node host.
 */
export async function renderAuditPdf(
  audit: Audit,
  content: AuditContent,
): Promise<Buffer> {
  const doc = new PDFDocument({
    size: "LETTER",
    margins: { top: 56, bottom: 56, left: 56, right: 56 },
    info: {
      Title: `Alivio Revenue Audit — ${audit.businessName}`,
      Author: "Alivio Search Cloud",
      Subject: "Revenue Leak Audit",
    },
  });

  const chunks: Buffer[] = [];
  doc.on("data", (c: Buffer) => chunks.push(c));
  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  const totalLoss = content.leaks.reduce(
    (s, l) => s + (Number.isFinite(l.estimatedMonthlyLossUsd) ? l.estimatedMonthlyLossUsd : 0),
    0,
  );

  const pageW = doc.page.width;
  const pageH = doc.page.height;
  const margin = 56;
  const contentW = pageW - margin * 2;

  // ---- Cover ----
  doc.rect(0, 0, pageW, pageH).fill(COLORS.bg);
  doc.fillColor(COLORS.accent).rect(0, 0, pageW, 8).fill();

  doc
    .fillColor(COLORS.mute)
    .font("Helvetica-Bold")
    .fontSize(11)
    .text("ALIVIO SEARCH CLOUD", margin, 80, { characterSpacing: 2 });

  doc
    .fillColor(COLORS.white)
    .font("Helvetica-Bold")
    .fontSize(34)
    .text("Revenue Leak Audit", margin, 110, { width: contentW });

  doc
    .fillColor(COLORS.text)
    .font("Helvetica")
    .fontSize(16)
    .text(audit.businessName, margin, 168, { width: contentW });

  doc
    .fillColor(COLORS.mute)
    .fontSize(11)
    .text(
      `Prepared for ${audit.leadName} · ${formatDate(audit.createdAt)}`,
      margin,
      192,
      { width: contentW },
    );

  // Headline loss card
  const cardY = 240;
  const cardH = 130;
  doc.roundedRect(margin, cardY, contentW, cardH, 14).fill(COLORS.card);
  doc.roundedRect(margin, cardY, contentW, cardH, 14).strokeColor(COLORS.border).lineWidth(1).stroke();
  doc.roundedRect(margin, cardY, 6, cardH, 3).fill(COLORS.accent);

  doc
    .fillColor(COLORS.mute)
    .font("Helvetica-Bold")
    .fontSize(10)
    .text("ESTIMATED MONTHLY REVENUE LEAK", margin + 24, cardY + 22, {
      characterSpacing: 1.5,
    });
  doc
    .fillColor(COLORS.white)
    .font("Helvetica-Bold")
    .fontSize(44)
    .text(formatUsd(totalLoss), margin + 24, cardY + 40);
  doc
    .fillColor(COLORS.text)
    .font("Helvetica")
    .fontSize(12)
    .text(
      `Across ${content.leaks.length} identified ${content.leaks.length === 1 ? "leak" : "leaks"} · ${formatUsd(totalLoss * 12)}/year`,
      margin + 24,
      cardY + 96,
    );

  // Summary
  doc
    .fillColor(COLORS.mute)
    .font("Helvetica-Bold")
    .fontSize(10)
    .text("EXECUTIVE SUMMARY", margin, cardY + cardH + 30, {
      characterSpacing: 1.5,
    });
  doc
    .fillColor(COLORS.text)
    .font("Helvetica")
    .fontSize(12)
    .text(content.summary, margin, cardY + cardH + 50, {
      width: contentW,
      lineGap: 3,
    });

  // Footer on cover
  doc
    .fillColor(COLORS.mute)
    .font("Helvetica")
    .fontSize(9)
    .text(
      "Confidential. Generated by Alivio Search Cloud — aliviosearch.com",
      margin,
      pageH - 36,
      { width: contentW, align: "center" },
    );

  // ---- Findings page(s) ----
  doc.addPage();
  doc.rect(0, 0, pageW, pageH).fill(COLORS.bg);

  let y = margin;
  doc
    .fillColor(COLORS.white)
    .font("Helvetica-Bold")
    .fontSize(22)
    .text("Top revenue leaks", margin, y);
  y += 36;

  for (let i = 0; i < content.leaks.length; i++) {
    const leak = content.leaks[i]!;
    const titleH = doc.heightOfString(leak.title, { width: contentW - 110 });
    const evidenceH = doc.heightOfString(leak.evidence, {
      width: contentW - 32,
    });
    const fixH = doc.heightOfString(leak.fix, { width: contentW - 32 });
    const blockH = 72 + titleH + evidenceH + fixH;

    if (y + blockH > pageH - 80) {
      doc.addPage();
      doc.rect(0, 0, pageW, pageH).fill(COLORS.bg);
      y = margin;
    }

    // card
    doc.roundedRect(margin, y, contentW, blockH, 12).fill(COLORS.card);
    doc.roundedRect(margin, y, contentW, blockH, 12).strokeColor(COLORS.border).lineWidth(1).stroke();

    // impact pill
    const pillW = 70;
    const pillX = margin + contentW - pillW - 16;
    const pillY = y + 16;
    doc.roundedRect(pillX, pillY, pillW, 20, 10).fill(impactColor(leak.impact));
    doc
      .fillColor(COLORS.white)
      .font("Helvetica-Bold")
      .fontSize(9)
      .text(leak.impact.toUpperCase(), pillX, pillY + 6, {
        width: pillW,
        align: "center",
        characterSpacing: 1,
      });

    // index + title
    doc
      .fillColor(COLORS.mute)
      .font("Helvetica-Bold")
      .fontSize(10)
      .text(`#${i + 1}`, margin + 20, y + 18);
    doc
      .fillColor(COLORS.white)
      .font("Helvetica-Bold")
      .fontSize(14)
      .text(leak.title, margin + 50, y + 14, { width: contentW - 130 });

    let yy = y + 18 + titleH + 12;

    // loss line
    doc
      .fillColor(COLORS.accent)
      .font("Helvetica-Bold")
      .fontSize(13)
      .text(
        `${formatUsd(leak.estimatedMonthlyLossUsd)} / month`,
        margin + 20,
        yy,
      );
    yy += 22;

    doc
      .fillColor(COLORS.mute)
      .font("Helvetica-Bold")
      .fontSize(9)
      .text("EVIDENCE", margin + 20, yy, { characterSpacing: 1.2 });
    yy += 12;
    doc
      .fillColor(COLORS.text)
      .font("Helvetica")
      .fontSize(11)
      .text(leak.evidence, margin + 20, yy, {
        width: contentW - 40,
        lineGap: 2,
      });
    yy += evidenceH + 10;

    doc
      .fillColor(COLORS.mute)
      .font("Helvetica-Bold")
      .fontSize(9)
      .text("FIX", margin + 20, yy, { characterSpacing: 1.2 });
    yy += 12;
    doc
      .fillColor(COLORS.text)
      .font("Helvetica")
      .fontSize(11)
      .text(leak.fix, margin + 20, yy, {
        width: contentW - 40,
        lineGap: 2,
      });

    y += blockH + 16;
  }

  // ---- Quick wins ----
  if (content.quickWins.length > 0) {
    if (y + 80 > pageH - 80) {
      doc.addPage();
      doc.rect(0, 0, pageW, pageH).fill(COLORS.bg);
      y = margin;
    }
    y += 12;
    doc
      .fillColor(COLORS.white)
      .font("Helvetica-Bold")
      .fontSize(18)
      .text("Quick wins to ship this week", margin, y);
    y += 28;

    for (const win of content.quickWins) {
      const winH = doc.heightOfString(win, { width: contentW - 36 });
      if (y + winH + 24 > pageH - 80) {
        doc.addPage();
        doc.rect(0, 0, pageW, pageH).fill(COLORS.bg);
        y = margin;
      }
      doc.circle(margin + 6, y + 8, 3).fill(COLORS.accent);
      doc
        .fillColor(COLORS.text)
        .font("Helvetica")
        .fontSize(11)
        .text(win, margin + 20, y, { width: contentW - 36, lineGap: 2 });
      y += winH + 14;
    }
  }

  // ---- Closing CTA ----
  if (y + 140 > pageH - 80) {
    doc.addPage();
    doc.rect(0, 0, pageW, pageH).fill(COLORS.bg);
    y = margin;
  }
  y += 24;
  doc.roundedRect(margin, y, contentW, 110, 14).fill(COLORS.accentSoft);
  doc.roundedRect(margin, y, contentW, 110, 14).strokeColor(COLORS.accent).lineWidth(1).stroke();
  doc
    .fillColor(COLORS.white)
    .font("Helvetica-Bold")
    .fontSize(16)
    .text("Ready to plug these leaks?", margin + 24, y + 22, {
      width: contentW - 48,
    });
  doc
    .fillColor(COLORS.text)
    .font("Helvetica")
    .fontSize(11)
    .text(
      "Reply to the email this PDF arrived in, or visit aliviosearch.com to install your AI Revenue Engine. We can have you running in days, not months.",
      margin + 24,
      y + 50,
      { width: contentW - 48, lineGap: 2 },
    );

  // page numbers
  const range = doc.bufferedPageRange();
  for (let p = 0; p < range.count; p++) {
    doc.switchToPage(range.start + p);
    doc
      .fillColor(COLORS.mute)
      .font("Helvetica")
      .fontSize(9)
      .text(
        `Page ${p + 1} of ${range.count}`,
        margin,
        pageH - 28,
        { width: contentW, align: "right" },
      );
  }

  doc.end();
  return done;
}

function formatDate(d: Date): string {
  return d.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}
